'use strict'
//total racks container
 const racks=[
    //Racks-1 container
    [
        //Shelf-1 Container
        [
            {
                medicineName:'med001',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med002',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med003',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-2 container
        [
            {
                medicineName:'med004',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med005',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med006',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-3 container
        [
            {
                medicineName:'med007',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med008',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med009',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ]
    ],
    //rack-2 container
    [
        //Shelf-1 Container
        [
            {
                medicineName:'med010',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med011',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med012',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-2 container
        [
            {
                medicineName:'med013',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med014',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med015',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-3 container
        [
            {
                medicineName:'med016',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med017',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med018',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ]
    ],
    //rack-3 container
    [
        //Shelf-1 Container
        [
            {
                medicineName:'med019',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med020',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med021',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-2 container
        [
            {
                medicineName:'med022',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med023',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med024',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-3 container
        [
            {
                medicineName:'med025',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med026',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med027',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ]
    ],
    //rack-4 container
    [
        //Shelf-1 Container
        [
            {
                medicineName:'med028',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med029',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med030',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-2 container
        [
            {
                medicineName:'med031',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med032',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med033',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-3 container
        [
            {
                medicineName:'med034',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med035',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med036',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ]
    ],
    //rack-5 container
    [
        //Shelf-1 Container
        [
            {
                medicineName:'med037',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med038',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med039',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-2 container
        [
            {
                medicineName:'med040',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med041',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med042',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-3 container
        [
            {
                medicineName:'med043',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med044',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med045',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ]
    ],
    //rack-6 container
    [
        //Shelf-1 Container
        [
            {
                medicineName:'med046',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med047',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med048',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-2 container
        [
            {
                medicineName:'med049',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med050',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med051',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-3 container
        [
            {
                medicineName:'med052',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med053',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med054',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ]
    ],
    //rack-7 container
    [
        //Shelf-1 Container
        [
            {
                medicineName:'med055',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med056',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med057',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-2 container
        [
            {
                medicineName:'med058',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med059',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med060',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-3 container
        [
            {
                medicineName:'med061',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med062',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med063',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ]
    ],
    //rack-8 container
    [
        //Shelf-1 Container
        [
            {
                medicineName:'med064',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med065',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med066',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-2 container
        [
            {
                medicineName:'med067',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med068',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med069',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-3 container
        [
            {
                medicineName:'med070',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med071',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med072',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ]
    ],
    //rack-9 container
    [
        //Shelf-1 Container
        [
            {
                medicineName:'med073',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med074',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med075',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-2 container
        [
            {
                medicineName:'med076',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med077',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med078',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ],
        //shelf-3 container
        [
            {
                medicineName:'med079',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med080',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
            {
                medicineName:'med081',
                totalCapacity:100,
                totalAvailableQuantity:function(){},
                notificationAlert:function(){},
            },
        ]
    ],
]
function search(value){
    let search = prompt("Enter the medicine name")
    let rackIndex = value.length
    for(let i=0; i<rackIndex; i++){
        let individualRack = value[i]
        for(let j=0; j<individualRack.length; j++){
            let individualshelf = individualRack[j]
            for(let k=0; k<individualshelf.length; k++){
                if(search === individualshelf[k].medicineName){
                    console.log(`Rack-number-${i+1},shelf-number-${j+1},container-number-${k+1}`)
                    console.log(individualshelf[k])
                }
            }
        }
    }
}
search(racks)